export const state = {
    bracket: [],
    currentRound: 0,
    currentMatch: 0,
    tourneyWinner: null,
    gameState: 'BRACKET',
    matchMode: 'TOURNAMENT',
    autoStartTimer: null,
    ball1: null,
    ball2: null,
    balls: [],
    projectiles: [],
    particles: [],
    floatingTexts: [],
    hazards: [],
    hexZones: [],
    hexProjectiles: [],
    trails: [],
    boomerangs: [],
    shields: [],
    portals: [],
    confetti: [],
    matchTime: 0,
    suddenDeath: false,
    shrinkInset: 0,
    speedMultiplier: 1,
    obstacles: []
};
