export const state = {
    bracket: [],
    currentRound: 0,
    currentMatch: 0,
    tourneyWinner: null,
    gameState: 'BRACKET',
    autoStartTimer: null,
    ball1: null,
    ball2: null,
    projectiles: [],
    particles: [],
    floatingTexts: [],
    hazards: [],
    confetti: [],
    matchTime: 0,
    suddenDeath: false,
    shrinkInset: 0,
    speedMultiplier: 1,
    obstacles: []
};
